### ISSUE TITLE
+ sign not always available on active session

### ISSUE THREAD

**Issue by tmbo** [muvr/muvr-ios#103]
I created a long session and added a couple of labels. After that I finished the session and started the next one (the data was not yet transmitted to the phone). I couldn't create labels for the new session because the button was disabled and it was still enabled for the previous session.

**Comment by tmbo** [comment]
This is probably only happening on #100

**Comment by samudurand** [comment]
It seems it does not happen anymore. Have you had the problem again @tmbo ?

**Comment by tmbo** [comment]
I guess we can close this one. Was fixed on the way of polishing #100
