### ISSUE TITLE
Android!

### ISSUE THREAD

**Issue by fommil** [muvr/muvr-ios#11]
please please please please

**Comment by janm399** [comment]
It's coming... There's a lot of programming to do, but it'll be there by Scala eXchange.

**Comment by fommil** [comment]
nice

**Comment by fommil** [comment]
have you tried any of the newer ENSIME clients yet? come join the party in gitter.

**Comment by teroxik** [comment]
@janm399 do you seriously need some help on this? Has anyone except me started to look at it? Do we have a fairly stable API now? :-)

**Comment by janm399** [comment]
API is now fairly good. We have good training API, and we're working on the on-device classification. (We have experiments in simple multi-layer perceptron network and SVM, both with acceptably good results.) We'll try it out first in iOS, then roll over to the C++ codebase. This should make it "easy" to use in Android.

**Comment by janm399** [comment]
I'll close this now, but there is https://github.com/muvr/muvr-ios, which I aim to have ready for #ScalaExchange
