### ISSUE TITLE
App freeze when exercise session grows

### ISSUE THREAD

**Issue by tmbo** [muvr/muvr-ios#121]
When training for a while the watch tends to freeze when looked at the app (probably because it is sending data or at least trying to do that). This is quite annoying since the display doesn't get updated and still shows the information from before it got turned of the last time.

**Comment by janm399** [comment]
It also crashes when the phone is not in reach. The crash for me usually happens about 25 minutes into the session.

**Comment by jamesfurness9** [comment]
Duc & I tried to replicate this today but couldn't. I ran a session for over 1 hour with the phone off and it seemed fine.
