### ISSUE TITLE
Calendar week switch doesn't work

### ISSUE THREAD

**Issue by tmbo** [muvr/muvr-ios#139]
How to reproduce:
- Select Sunday of the current week
- Flip to go to the previous week
- Try to get back to the current week (this will only work after selecting a different day that is not sunday)

**Comment by duchoang** [comment]
Have you tested with the latest code, I tried again and it's ok. It maybe the same with this bug: https://github.com/muvr/muvr-ios/issues/131 (fixed)

**Comment by tmbo** [comment]
I think i have the latest version installed. It works for all days but Sunday.
