### ISSUE TITLE
App frozen at application start after collecting a bunch of sessions

### ISSUE THREAD

**Issue by tmbo** [muvr/muvr-ios#17]
After collecting some sessions, including long ones (about 20 minutes), starting the app takes quite some time and interface is frozen during that time.

I am not quite sure what is happening in the background.

**Comment by janm399** [comment]
Part of the problem is the debugging output, and the immense waste of JSON to transmit the accelerometer data. Instead of ~ 5B per sample, we have, for example ``{"x":1000,"y":334,"z":244}``, 30-odd bytes.

**Comment by tmbo** [comment]
I deactivated the logging on `develop` so that should be better. I don't quite get what is getting transmitted when starting the application?

**Comment by janm399** [comment]
Everything that's not yet synchronized. It's actually on show of the home view.
