### ISSUE TITLE
Fusion of sets of different sessions on home screen

### ISSUE THREAD

**Issue by tmbo** [muvr/muvr-ios#30]
I am creating a session of two sets. Go to home screen: one row with two exercises. I create another session with three sets. Going to the home screen results in the first row showing three exercises and the second row showing 5.

**Comment by janm399** [comment]
There is a test that shows a problem **on 32bit ARM devices**. The code works in the simulator and on 64bit ARM device.

**Comment by tmbo** [comment]
I fixed the issue and it actually didn't have to do anything with 32 vs 64. The pebble handler for the session wasn't disconnected and therefore when a new session got created we ended up with two `MRPebbleDeviceSession` both handling the messages. Therefore, I have no idea why it worked on your device.

**Comment by janm399** [comment]
Brilliant. And sorry for side-tracking you.
