### ISSUE TITLE
iOS app crashes on iPhone 5 when it receives data from the watch

### ISSUE THREAD

**Issue by by-dam** [muvr/muvr-ios#55]

**Comment by tmbo** [comment]
`EXC_BAD_ACCESS` in `MKSensorData init` int `L57` when trying to access `bytes.next()` for `start`.

Seems to be an alignment issue.

**Comment by samudurand** [comment]
We thought it could have something to do with 32 and 64 bits systems but 5S is x64 isn't it ?
